
char campaign_manager_DEFAULTDB_maps[][MAPNAME_SIZE] = {
    "# Lines starting with \"#\" get ignored, as so do empty lines",
    "# Lines starting with \"@\" mark a campaign name",
    "# Lines starting with \"$\" mark a survival map",
    "# If any of the maps are missing, they will be ignored",
    "",
    "# Official: L4D1",
    "",
    "@No Mercy", "c8m1_apartment", "c8m2_subway", "c8m3_sewers", "c8m4_interior", "c8m5_rooftop", "$c8m2_subway",
    "@Crash Course", "c9m1_alleys", "c9m2_lots",
    "@Death Toll", "c10m1_caves", "c10m2_drainage", "c10m3_ranchhouse", "c10m4_mainstreet", "c10m5_houseboat",
    "@Dead Air", "c11m1_greenhouse", "c11m2_offices", "c11m3_garage", "c11m4_terminal", "c11m5_runway",
    "@Blood Harvest", "c12m1_hilltop", "c12m2_traintunnel", "c12m3_bridge", "c12m4_barn", "c12m5_cornfield",
    "@The Sacrifice", "c7m1_docks", "c7m2_barge", "c7m3_port",
    "@The Last Stand", "c14m1_junkyard", "c14m2_lighthouse",
    "",
    "# Official: L4D2",
    "",
    "@Dead Center", "c1m1_hotel", "c1m2_streets", "c1m3_mall", "c1m4_atrium",
    "@The Passing", "c6m1_riverbank", "c6m2_bedlam", "c6m3_port",
    "@Dark Carnival", "c2m1_highway", "c2m2_fairgrounds", "c2m3_coaster", "c2m4_barns", "c2m5_concert",
    "@Swamp Fever", "c3m1_plankcountry", "c3m2_swamp", "c3m3_shantytown", "c3m4_plantation",
    "@Hard Rain", "c4m1_milltown_a", "c4m2_sugarmill_a", "c4m3_sugarmill_b", "c4m4_milltown_b", "c4m5_milltown_escape",
    "@The Parish", "c5m1_waterfront", "c5m2_park", "c5m3_cemetery", "c5m4_quarter", "c5m5_bridge",
    "@Cold Stream", "c13m1_alpinecreek", "c13m2_southpinestream", "c13m3_memorialbridge", "c13m4_cutthroatcreek",
    "",
    "# Addon: Nightmare",
    "",
    "@[addon] No Mercy: Rehab", "nmrm1_apartment", "nmrm2_subway", "nmrm3_sewers", "nmrm4_hospital", "nmrm5_rooftop",
    "@[addon] Dark Center", "c1m1d_hotel", "c1m2d_streets", "c1m3d_mall", "c1m4d_atrium",
    "@[addon] Deadbeat Escape", "deadbeat01_forest", "deadbeat02_alley", "deadbeat03_street", "deadbeat04_park",
    "@[addon] The Dark Parish", "c5m1_darkwaterfront", "c5m2_darkpark", "c5m3_darkcemetery", "c5m4_darkquarter", "c5m5_darkbridge",
    "@[addon] Fairfield Terror", "ft_m1_apartments_08_a", "ft_m2_subway_08_a", "ft_m3_sewers_08_b", "ft_m4_hospital_08_a", "ft_m5_rooftop_08_a",
    "@[addon] Hopeless", "hopeless_m1", "hopeless_m2", "hopeless_m3",
};

#define campaign_manager_DEFAULTDB_maps_len (sizeof(campaign_manager_DEFAULTDB_maps))
